### ISSUE TITLE
Ejecución del programa en RPi3 sin puerto serie

### ISSUE THREAD

**Issue by gonzafernan** [FrancoPalau/Computer-Vision-Solar-Sensor#3]
Las dependencias (OpenCV y Numpy) ya están funcionando. Modifiqué el archivo main.py para no considerar el puerto serie, pero me tira un error en la linea 28:

```
Unable to stop the stream: Invalid argument
Traceback (most recent call last):
    File "main.py", line 28, in <module>
        output = frame.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

Verificar el código en branch *rpi-test*. El siguiente código funciona perfecto:

``` python
import numpy as np
import cv2

cap = cv2.VideoCapture('vtest.avi')

while(cap.isOpened()):
    ret, frame = cap.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

**Comment by FrancoPalau** [comment]
El imshow te muestra la imagen en escala de grises correctamente? Si es así, me parece muy extraño porque frame, segun el error, es un 'NonType' object.
 A mi me ha tirado ese error antes, cuando en el VideoCapture me equivocaba de cámara y como resultado frame terminaba siendo un NonType object, pero siempre lo he probado con camaras, nunca con videos (veo que vos estas usando "vtest.avi"). Proba si dandole a VideoCapture la camara te funciona.
No se como las mapea la RPi3 a las cámaras. En mi compu es simplemente el valor 0 para la cámara integrada, 1 para USB. Fijate eso y decime si sigue el error
Edit:
Encontré esto:
If you try to call the .read  method of an instantiated cv2.VideoCapture  (regardless if it’s a video file or webcam stream) and notice a NoneType  error or  AssertionError , then you likely have a problem with either:

    The path to your input video file (it’s probably incorrect).
    Not having the proper video codecs installed, in which case you’ll need to install the codecs, followed by re-compiling and re-installing OpenCV (see this page for a complete list of tutorials).
    Your webcam not being accessible via OpenCV. This could be for any number of reasons, including missing drivers, an incorrect index passed to cv2.VideoCapture , or simply your webcam is not properly attached to your system.

aca: https://www.pyimagesearch.com/2016/12/26/opencv-resolving-nonetype-errors/

**Comment by gonzafernan** [comment]
Excelente! [Solucioné el problema](https://github.com/FrancoPalau/Computer-Vision-Solar-Sensor/commit/d14603adaa67dfdbbd76c78ad1d606150bb26c7c). Tenías razón, el parámetro de *VideoCapture* era 0:

```
cap = cv2.VideoCapture(0)
```
Solo para tener en cuenta, en este momento el programa corre mucho más lento que, por ejemplo, en mi computadora. Problema solucionado, el programa está funcionando. Cierro el issue.
